### PR TITLE
Add dnf package manager to package manager checks

### PR DESCRIPTION
**Pull request by esarver**

### CODE REVIEW

**Comment by chrisparnin** [comment]
@esarver This would be a reasonable addition.

**Comment by esarver** [comment]
Sorry, the reason I closed it was because I hadn't yet tested it from my repo. I meant to merge it into main on my fork.

**Comment by chrisparnin** [comment]
You should be able to download/copy the yaml file and run like this locally:

```
opunit verify local -c 519.yml
```

**Comment by esarver** [comment]
Ok. This should be ready. At least for those with an up-to-date version of Fedora 35. This may exclude anyone using Fedora 34 or RHEL (or a clone thereof).

**Pull request merged**
